version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend/uploads:/app/uploads

volumes:
  uploads:
