[project]
name = "insurace-bot"
version = "0.1.0"
description = "Let's build a insurance bot that helps people understand the policies better."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.112.1",
]
